### ISSUE TITLE
Updating the git tree failed

### ISSUE THREAD

**Issue by moses-aronov** [letmaik/vscode-git-tree-compare#30]
Every time I try to use git tree compare I get this error from vscode

Updating the git tree failed: ENOENT: no such file or directory '/website/.git/refs/heads/...'

**Comment by letmaik** [comment]
Can you tell me a little bit about your environment? Which OS are you using? And which git version? And can you check for me whether the folder `/website/.git/refs/heads/` exists?

**Comment by letmaik** [comment]
I'm closing this now. If you still have the same problem, please reopen and provide more details about your setup.

**Comment by Oldself** [comment]
Hi, I think I encounter the same issue as @moses-aronov and I have a clue as to what is causing the problem. 

I have a project in which Git Tree Compare stopped working and keeps producing the error *Updating the git tree failed: ENOENT: no such file or directory, open xxxxx\\.git\refs\heads\develop'*

In this project the heads directory is empty and I think this is because the size of the project has crossed a threshold and git now manages its internal data differently as explained here: https://stackoverflow.com/a/30143136/1826063 and, indeed, I do have a .git/packed-refs file now in this project.

I hope this helps.

**Comment by letmaik** [comment]
Fixed in the latest release of the extension.
