### ISSUE TITLE
add staged/unstaged/partialy-staged status

### ISSUE THREAD

**Issue by ngmariusz** [letmaik/vscode-git-tree-compare#36]
i would  drop native vscode git view for good if git-tree-compare   helps me with that.

btw. great idea with filtering files; in times of monorepos - super usefull

**Comment by letmaik** [comment]
I'd like to know a little bit more about your use case. Personally I never saw the extension as a replacement for the regular git tab but rather as a complementary feature since it let's you diff against branches and not just against the current state of the repo -- the latter is only good for single-commit preparation.
Since this extension will never integrate features that do things like stage or commit you would use the regular git view anyway for that. The question is, how much do you gain in displaying the fact that something is staged within the git tree view? The normal file explorer only distinguishes that in the file tooltips with "Index Modified" vs "Modified" but I honestly never looked at those tooltips.

**Comment by letmaik** [comment]
Closing this for now, but feel free to add further comments if you still think it's a good idea.
